slack:
  bot_token: SLACK_BOT_TOKEN
  app_token: SLACK_APP_TOKEN
  report_channel: SLACK_REPORT_CHANNEL
  report_channel_id: SLACK_REPORT_CHANNEL_ID

jira:
  project: JIRA_PROJECT

secrets:
  cftptl-intsvc:
    jira-username: JIRA_USERNAME
    jira-api-token: JIRA_API_TOKEN
    possessions-slack-bot-token: SLACK_BOT_TOKEN
    possessions-slack-app-token: SLACK_APP_TOKEN